'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../frontend/index.html'),'utf8');
const source=html.slice(html.indexOf('/* Centro de costos y gastos: datos confirmados'),html.lastIndexOf('</script>'));
function context(overrides={}){const nodes={};const ctx=vm.createContext({Intl,Date,JSON,Number,String,URL,Blob,crypto:{randomUUID:()=> 'business-ui-operation-0001'},AUTH_TOKEN:'test-token',currentView:'control-gastos',document:{getElementById:id=>nodes[id]||(nodes[id]={value:'',textContent:'',innerHTML:'',disabled:false,isConnected:true,addEventListener(){}}),querySelectorAll:()=>[]},window:{addEventListener(){}},setTimeout(){},isGerente:()=>true,esFacturacion:()=>false,toast(){},...overrides});vm.runInContext(source,ctx);ctx.nodes=nodes;return ctx;}
function form(ctx){vm.runInContext("BC.editor={kind:'expense',data:{attachment:null}};BC.kind='expense';",ctx);const values={bcDate:'2026-09-20',bcAmount:'85.50',bcCat:'Marketing',bcArea:'Marketing',bcState:'pendiente',bcTreatment:'operativo',bcResponsible:'Sergio',bcPayee:'Proveedor',bcReference:'',bcOrder:'',bcDescription:'Campaña'};for(const [id,v] of Object.entries(values))ctx.document.getElementById(id).value=v;}
test('formulario de gastos sin adjunto se guarda y reintento mantiene operación e importe',async()=>{const sent=[];let fail=true,loaded=0;const c=context({apiPost:async(url,b)=>{sent.push(JSON.parse(JSON.stringify(b)));if(fail)throw Error('Red interrumpida');return {id:1};}});form(c);c.bcLoad=async()=>{loaded++;};await c.bcSave();assert.equal(c.nodes.bcFields.disabled,true);assert.equal(c.nodes.bcSaveButton.textContent,'Reintentar guardado');assert.equal(sent[0].data.attachment,null);assert.equal(sent[0].data.category,'Marketing');assert.equal(loaded,0);c.nodes.bcAmount.value='500';fail=false;await c.bcSave();assert.equal(sent[1].data.amount,'85.50');assert.equal(sent[1].operation_key,sent[0].operation_key);assert.equal(loaded,1);});
test('rechazo por conflicto permite volver a abrir sin falso mensaje de guardado',async()=>{let success=0;const c=context({apiPost:async()=>{throw Object.assign(Error('Otra persona actualizó'),{status:409});},toast(){success++;}});form(c);await c.bcSave();assert.equal(c.nodes.bcFields.disabled,false);assert.equal(success,0);assert.match(c.nodes.bcStatus.textContent,/Otra persona/);});
test('fallo al adjuntar no borra el respaldo anterior ni impide guardar sin uno',async()=>{const c=context({uploadRealFile:async()=>{throw Error('Archivo vacío');}});form(c);const input={files:[{name:'empty.pdf'}],value:'empty.pdf'};await c.bcAttach(input);assert.equal(input.value,'');assert.equal(c.nodes.bcSaveButton.disabled,false);assert.match(c.nodes.bcStatus.textContent,/Archivo vacío/);assert.equal(vm.runInContext('BC.editor.data.attachment',c),null);});
test('gastos ingresados como texto no ejecutan HTML',()=>{const c=context();assert.equal(c.bcEsc('<img src=x onerror=alert(1)>'),'&lt;img src=x onerror=alert(1)&gt;');assert.equal(c.bcEsc('" onclick="x'),'&quot; onclick=&quot;x');});
test('consulta anterior no sobrescribe una pantalla nueva',async()=>{let resolve;const c=context({apiGet:()=>new Promise(r=>{resolve=r;})});const p=c.bcLoad('expense');c.nodes.bcRoot.isConnected=false;resolve({rows:[],summary:{}});await p;assert.equal(c.nodes.bcRoot.innerHTML,'');});
test('todos los scripts del HTML compilan y los formularios están protegidos del refresco automático',()=>{for(const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))new vm.Script(match[1]);const declaration=html.match(/const VISTAS_FORMULARIO=(\[[^;]+\]);/)[1];assert.ok(declaration.includes('centro-costos'));assert.ok(declaration.includes('control-gastos'));});
