'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../lib/business-control-core'),service=require('../lib/business-control');
const inventory=[{id:1,tipo:'materia_prima',nombre:'Azúcar',unidad:'kg',costo_prom:'2.000000'},{id:2,tipo:'materia_prima',nombre:'Sabor',unidad:'L',costo_prom:'10.000000'}];
const formula=()=>({name:'YumYum 5 kg',product_id:1,yield_quantity:2,yield_unit:'funda de 5 kg',yield_kg:10,sale_price:20,labor:3,overhead:1,lines:[{mode:'inventory',kind:'material',item_id:1,quantity:10000,unit:'g'},{mode:'inventory',kind:'material',item_id:2,quantity:100,unit:'ml'},{mode:'manual',kind:'packaging',name:'Funda',quantity:2,unit:'u',unit_cost:.1}]});
const expense=()=>({date:'2026-09-20',amount:85.50,category:'Marketing',area:'Marketing',description:'Campaña de lanzamiento',responsible:'Sergio',status:'pendiente',treatment:'operativo'});
test('convierte unidades, usa rendimiento vendible e incluye empaque y fabricación',()=>{const c=core.calculate(core.formula(formula()),inventory);assert.equal(c.complete,true);assert.equal(c.total,25.2);assert.equal(c.per_unit,12.6);assert.equal(c.per_kg,2.52);assert.equal(c.margin_percent,37);assert.equal(c.lines[1].inventory_quantity,.1);});
test('cambio de costo promedio recalcula sin alterar fotografía previa',()=>{const f=core.formula(formula()),old=core.calculate(f,inventory),next=core.calculate(f,inventory.map(x=>({...x,costo_prom:4})));assert.equal(old.total,25.2);assert.equal(next.total,44.6);});
test('sin costo no presenta un total ni margen engañosos',()=>{const c=core.calculate(core.formula(formula()),inventory.map(i=>({...i,costo_prom:0})));assert.equal(c.complete,false);assert.equal(c.total,null);assert.equal(c.per_unit,null);assert.equal(c.margin_percent,null);assert.equal(c.missing.length,2);});
test('no convierte volumen en masa ni usa productos terminados como materia prima',()=>{assert.throws(()=>core.convert(1,'L','kg'),/No se puede/);const f=formula();f.lines[0].unit='L';assert.equal(core.calculate(core.formula(f),inventory).complete,false);assert.equal(core.calculate(core.formula(formula()),inventory.map(i=>({...i,tipo:'producto_terminado'}))).complete,false);});
test('rendimiento inválido, línea vacía y precio manual de materia prima se rechazan',()=>{assert.throws(()=>core.formula({...formula(),yield_quantity:0}),/Rendimiento/);assert.throws(()=>core.formula({...formula(),lines:[]}),/Incluye/);const f=formula();f.lines[0]={mode:'manual',kind:'material',quantity:1,unit:'kg'};assert.throws(()=>core.formula(f),/vincularse/);});
test('gasto Marketing sin respaldo y posterior respaldo HTTPS',()=>{const e=core.expense(expense());assert.equal(e.attachment,null);assert.equal(e.category,'Marketing');assert.equal(core.expense({...e,attachment:{url:'https://example.test/a.pdf',name:'Factura.pdf'}}).attachment.name,'Factura.pdf');});
test('rechaza fechas imposibles, fracciones de centavo y URL ejecutable',()=>{assert.throws(()=>core.expense({...expense(),date:'2026-02-30'}),/Fecha/);assert.throws(()=>core.expense({...expense(),amount:1.001}),/decimales/);assert.throws(()=>core.expense({...expense(),attachment:{url:'javascript:alert(1)',name:'x'}}),/Adjunto/);assert.throws(()=>core.expense({...expense(),category:'Inventario'}),/Categoría/);});
test('totales excluyen anulados y separan pagos, fabricación y responsables',()=>{const rows=[core.expense(expense()),core.expense({...expense(),amount:10,status:'pagado',treatment:'fabricacion'}),core.expense({...expense(),amount:100,status:'anulado'})];const t=core.totals(rows);assert.equal(t.total,95.5);assert.equal(t.pending,85.5);assert.equal(t.paid,10);assert.equal(t.operating,85.5);assert.equal(t.manufacturing,10);assert.equal(t.categories[0].total,95.5);assert.equal(t.responsibles[0].name,'Sergio');});
test('mes anterior cruza año correctamente',()=>{assert.deepEqual(service.monthRange('2026-01'),{start:'2026-01-01',end:'2026-02-01',previous:'2025-12-01'});assert.throws(()=>service.monthRange('2026-13'),/Mes/);});
function database(role='gerente'){
 const store={formulas:[],expenses:[],audit:[],ops:[],role,inventory:structuredClone(inventory),queries:[],failAudit:false};let backup;
 const db={release(){},async query(sql,p=[]){store.queries.push(sql);const result=rows=>({rows:structuredClone(rows)});
 if(sql==='BEGIN'){backup=structuredClone({formulas:store.formulas,expenses:store.expenses,audit:store.audit,ops:store.ops});return result([]);}
 if(sql==='ROLLBACK'){Object.assign(store,backup);return result([]);}if(sql==='COMMIT'||sql.includes('pg_advisory'))return result([]);
 if(sql.startsWith('SELECT id,name,username,role FROM users'))return result(store.role?[{id:1,name:'Gerencia',role:store.role}]:[]);
 if(sql.startsWith('SELECT * FROM business_operations'))return result(store.ops.filter(o=>o.operation_key===p[0]));
 if(sql.includes('FROM inventario'))return result(store.inventory);
 if(sql.includes('FROM catalogo'))return result([{id:1,nombre:'YumYum 5 kg'}]);
 if(sql.includes('FROM pedidos')){assert.ok(sql.includes('numero_pedido=$1'));return result(p[0]==='CT-1'?[{id:17}]:[]);}
 if(sql.startsWith('SELECT * FROM cost_formulas')||sql.startsWith('SELECT * FROM business_expenses')){const a=sql.includes('cost_formulas')?store.formulas:store.expenses;return result(a.filter(r=>r.id===p[0]));}
 if(sql.startsWith('INSERT INTO cost_formulas')||sql.startsWith('INSERT INTO business_expenses')){const isCost=sql.includes('cost_formulas'),a=isCost?store.formulas:store.expenses;const r={id:a.length+1,data:JSON.parse(p[0]),version:1,updated_at:'2026-09-20T12:00:00Z'};if(isCost)r.snapshot=JSON.parse(p[1]);a.push(r);return result([r]);}
 if(sql.startsWith('UPDATE cost_formulas')||sql.startsWith('UPDATE business_expenses')){const isCost=sql.includes('cost_formulas'),a=isCost?store.formulas:store.expenses,r=a.find(r=>r.id===p[isCost?2:1]);r.data=JSON.parse(p[0]);r.version++;if(isCost)r.snapshot=JSON.parse(p[1]);return result([r]);}
 if(sql.startsWith('INSERT INTO business_audit')){if(store.failAudit)throw Error('fallo audit');store.audit.push({entity:p[0],before:JSON.parse(p[5]),after:JSON.parse(p[6])});return result([]);}
 if(sql.startsWith('INSERT INTO business_operations')){store.ops.push({operation_key:p[0],actor_id:p[1],request_hash:p[2],response:JSON.parse(p[3])});return result([]);}
 throw Error('SQL inesperado: '+sql);
 }};return {store,query:db.query,connect:async()=>db};
}
const body=(data,key='operation-business-00001')=>({data,operation_key:key});
test('guardar gasto sin archivo persiste y reintento devuelve el mismo registro',async()=>{const db=database('facturacion'),b=body(expense());const one=await service.save(db,1,'expense',b),two=await service.save(db,1,'expense',b);assert.equal(one.id,two.id);assert.equal(db.store.expenses.length,1);assert.equal(db.store.audit.length,1);assert.equal(db.store.expenses[0].data.attachment,null);});
test('reutilizar operación para otro importe se rechaza',async()=>{const db=database();await service.save(db,1,'expense',body(expense()));await assert.rejects(service.save(db,1,'expense',body({...expense(),amount:100})),{status:409});assert.equal(db.store.expenses[0].data.amount,85.5);});
test('vendedor no registra gastos, facturación no ve costos, usuario eliminado no opera',async()=>{await assert.rejects(service.save(database('vendedor'),1,'expense',body(expense())),{status:403});await assert.rejects(service.actor(database('facturacion'),1,true),{status:403});await assert.rejects(service.save(database(null),1,'expense',body(expense())),{status:401});});
test('edición auditable permite anular y exige versión y motivo',async()=>{const db=database();await service.save(db,1,'expense',body(expense()));const b={...body({...expense(),status:'anulado'},'operation-business-00002'),id:1,version:1,reason:'Registro duplicado'};const r=await service.save(db,1,'expense',b);assert.equal(r.version,2);assert.equal(db.store.audit[1].before.data.status,'pendiente');assert.equal(db.store.audit[1].after.data.status,'anulado');await assert.rejects(service.save(db,1,'expense',{...b,operation_key:'operation-business-00003'}),{status:409});await assert.rejects(service.save(db,1,'expense',{...b,reason:''}),/Motivo/);});
test('fallo de historial revierte gasto y operación',async()=>{const db=database();db.store.failAudit=true;await assert.rejects(service.save(db,1,'expense',body(expense())),/fallo audit/);assert.equal(db.store.expenses.length,0);assert.equal(db.store.ops.length,0);assert.ok(db.store.queries.includes('ROLLBACK'));});
test('pedido opcional se valida cuando está presente',async()=>{const db=database();await assert.rejects(service.save(db,1,'expense',body({...expense(),order_id:'NO-EXISTE'})),/no existe/);assert.equal(db.store.expenses.length,0);await service.save(db,1,'expense',body({...expense(),order_id:'CT-1'}));assert.equal(db.store.expenses.length,1);});
test('fotografía de fórmula se calcula en servidor y se conserva en historial',async()=>{const db=database();const b=body(formula());b.data.total=.01;const first=await service.save(db,1,'formula',b);assert.equal(first.snapshot.total,25.2);db.store.inventory[0].costo_prom=3;const second=await service.save(db,1,'formula',{...body(formula(),'operation-business-00002'),id:1,version:1,reason:'Actualizar costos'});assert.equal(second.snapshot.total,35.2);assert.equal(db.store.audit[1].before.snapshot.total,25.2);assert.ok(db.store.queries.some(s=>s.includes('FOR UPDATE')));});
module.exports={database,formula,expense};
