'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../frontend/index.html'),'utf8');
function context(){const nodes={};const c=vm.createContext({Intl,Date,window:{addEventListener(){}},document:{getElementById:id=>nodes[id]||(nodes[id]={innerHTML:'',addEventListener(){},disabled:false}),querySelectorAll:()=>[]}});vm.runInContext(html.slice(html.indexOf('/* Centro de costos y gastos: datos confirmados'),html.lastIndexOf('</script>')),c);c.nodes=nodes;return c;}
function runSubmit(c,markup,fn){const scope={};for(const m of markup.matchAll(/\bid="([^"]+)"/g))scope[m[1]]={tag:'element'};c.formScope=scope;let called=0;c[fn]=()=>{called++;};const code=markup.match(/onsubmit="([^"]+)"/)[1];vm.runInContext('function submitEvent(event){with(formScope){'+code+'}};submitEvent({preventDefault(){}})',c);return called;}
test('Guardar ficha ejecuta el manejador incluso con acceso por nombre a controles del formulario',()=>{const c=context();vm.runInContext("PM.editor={id:1,version:1,nombre:'YumYum',sku:'CT-P-1',activo:true,ficha:{}};PM.categories=[];PM.formulations=[];pmForm();",c);const markup=c.nodes.pmRoot.innerHTML;assert.equal(runSubmit(c,markup,'pmSave'),1);assert.ok(!markup.includes('id="pmSave"'));assert.ok(!markup.includes('id="pmBack"'));});
test('regresión reproduce el bloqueo anterior al introducir el ID conflictivo',()=>{const c=context();vm.runInContext("PM.editor={nombre:'YumYum',activo:true,ficha:{}};pmForm();",c);const old=c.nodes.pmRoot.innerHTML.replace('id="pmSaveButton"','id="pmSave"');assert.throws(()=>runSubmit(c,old,'pmSave'),/not a function/);});
test('Guardar gasto y costeo evita el mismo conflicto',()=>{const c=context();vm.runInContext("BC.editor={kind:'expense',data:{}};BC.data={categories:[],areas:[]};bcRenderEditor();",c);assert.equal(runSubmit(c,c.nodes.bcRoot.innerHTML,'bcSave'),1);assert.ok(!c.nodes.bcRoot.innerHTML.includes('id="bcCancel"'));});
test('Formulaciones usa submit con listener y figura en la categoría Productos y costos',()=>{assert.match(html,/views:\['mis-productos','formulaciones','centro-costos'\]/);assert.match(html,/form.addEventListener\('submit',event=>\{event.preventDefault\(\);bfSave\(\);\}\)/);});
