'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {prepare,record}=require('../lib/historical-dispatch');
const user={id:1,name:'Gerencia',role:'gerente'},body={fecha:'2026-09-18',motivo:'Mercancía despachada previamente; registro pendiente.'},now=new Date('2026-10-02T19:00:00Z');
const row=()=>({id:5,numero_pedido:'CT-2026-01206',factura:'001-001-9134',estado:'POR_ENTREGAR',products:[{name:'Acidazo',qty:20,price:10}],pago:{saldo:230},financial_data:{events:[]},history:[],entregas:[{numeroFactura:'001-001-9134',estado:'POR_DESPACHAR',items:[{name:'Acidazo',qty:20}]}]});
test('registra fecha y autor, conserva ítems y no altera valores',()=>{const r=row(),copy=structuredClone(r),n=prepare(r,body,user,now);assert.deepEqual(r,copy);assert.equal(n.estado,'EN_TRANSITO');assert.deepEqual(n.entregas[0].items,r.entregas[0].items);assert.equal(n.entregas[0].despachoHistorico.fecha,body.fecha);assert.match(n.history[0].note,/sin movimiento de inventario/);assert.equal(n.history[0].actor,'Gerencia · Gerencia');assert.deepEqual(Object.keys(n).sort(),['entregas','estado','history']);assert.equal(prepare({...r,...n},body,user,now),null);});
test('permite los cuatro pedidos y verifica su factura',()=>{for(const [id,invoice] of Object.entries({'CT-2026-01206':'001-001-9134','CT-2026-01187':'001-001-9150','CT-2026-01185':'001-001-9113','CT-2026-01184':'001-001-9110'})){assert.equal(prepare({...row(),numero_pedido:id,factura:invoice,entregas:[]},body,user,now).estado,'EN_TRANSITO');}assert.throws(()=>prepare({...row(),factura:'otra',entregas:[]},body,user,now),/no coincide/);});
test('rechaza otros perfiles, pedidos, fechas, motivos y estados',()=>{assert.throws(()=>prepare(row(),body,{...user,role:'bodega'},now),/Gerencia/);assert.throws(()=>prepare({...row(),numero_pedido:'CT-2026-99999'},body,user,now),/habilitado/);for(const fecha of ['2026-02-30','2027-01-01',''])assert.throws(()=>prepare(row(),{...body,fecha},user,now),/fecha/);assert.throws(()=>prepare(row(),{...body,motivo:''},user,now),/motivo/);assert.throws(()=>prepare({...row(),estado:'ENTREGADO'},body,user,now),/estado/);});
test('otra factura pendiente conserva estado pendiente y no cambia su entrega',()=>{const r=row();r.entregas.push({numeroFactura:'otra',estado:'POR_DESPACHAR',items:[]});const n=prepare(r,body,user,now);assert.equal(n.estado,'POR_ENTREGAR');assert.deepEqual(n.entregas[1],r.entregas[1]);});
function fake(failAudit=false){let current=row(),backup,updates=0,audits=0;const calls=[];const db={release(){},async query(sql,args){calls.push(sql);if(sql==='BEGIN'){backup=structuredClone(current);return {rows:[]};}if(sql==='ROLLBACK'){current=backup;return {rows:[]};}if(sql==='COMMIT')return {rows:[]};if(sql.startsWith('SELECT id,name'))return {rows:[user]};if(sql.startsWith('SELECT * FROM pedidos'))return {rows:[structuredClone(current)]};if(sql.startsWith('UPDATE pedidos')){updates++;current={...current,estado:args[0],entregas:JSON.parse(args[1]),history:JSON.parse(args[2])};return {rows:[structuredClone(current)]};}if(sql.startsWith('INSERT INTO business_audit')){if(failAudit)throw Error('audit failed');audits++;return {rows:[]};}throw Error('Unexpected SQL: '+sql);}};return {connect:async()=>db,calls,get current(){return current;},get updates(){return updates;},get audits(){return audits;}};}
test('transacción bloquea pedido, audita una vez y nunca escribe inventario',async()=>{const db=fake();await record(db,1,row().numero_pedido,body);await record(db,1,row().numero_pedido,body);assert.equal(db.updates,1);assert.equal(db.audits,1);assert.ok(db.calls.some(s=>s.includes('FOR UPDATE')));assert.ok(!db.calls.some(s=>/inventario|movimientos/.test(s)));assert.deepEqual(db.current.pago,row().pago);assert.deepEqual(db.current.financial_data,row().financial_data);});
test('fallo de auditoría revierte el cambio de estado',async()=>{const db=fake(true);await assert.rejects(record(db,1,row().numero_pedido,body),/audit failed/);assert.deepEqual(db.current,row());});
