const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../frontend/index.html'),'utf8');
function setup(){const nodes={edit_discount:{value:'10'},edit_discount_reason:{value:'Acuerdo comercial'},edit_discount_amount:{},edit_subtotal:{},edit_total:{}};const order={id:'CT-1',products:[{name:'Yum',qty:10,price:10}],subtotal:100,descuento:0,ivaTasa:15,state:'POR_FACTURAR',history:[]};const c=vm.createContext({document:{getElementById:id=>nodes[id]},ORDERS:[order],editPedidoId:'CT-1',editLines:[{name:'Yum',qty:10,price:10}],currentRole:'gerente_proy',money:n=>n,guardDouble:()=>false,releaseGuard(){},tieneEntregas:()=>false,minQtyEditLine:()=>0,myName:()=> 'Gerencia',ahoraStr:()=> 'hoy',toast(){},closeModal(){},renderView(){},buildNav(){},mapPedido:r=>({...r,id:r.numero_pedido}),actualizarResumenPedido(){}});
vm.runInContext(html.slice(html.indexOf('function computeTotals('),html.indexOf('function recalcPago(')),c);
vm.runInContext(html.slice(html.indexOf('function updateEditTotals('),html.indexOf('function openEditarProductos(')),c);
vm.runInContext(html.slice(html.indexOf('async function confirmEditarProductos('),html.indexOf('function openFacturar(')),c);
return {c,nodes,order};}
test('vista previa calcula descuento antes del IVA y permite quitarlo',()=>{const {c,nodes}=setup();c.updateEditTotals();assert.equal(nodes.edit_total.textContent,103.5);assert.equal(nodes.edit_discount_amount.textContent,10);nodes.edit_discount.value='0';c.updateEditTotals();assert.equal(nodes.edit_total.textContent,115);});
test('envía descuento y motivo y espera confirmación antes de actualizar pedido',async()=>{const {c,order}=setup();let resolve;c.apiPut=async(url,b)=>{assert.equal(b.descuento,10);assert.equal(b.descuento_motivo,'Acuerdo comercial');return new Promise(r=>resolve=()=>r({...b,numero_pedido:'CT-1'}))};const p=c.confirmEditarProductos();assert.equal(order.descuento,0);resolve();await p;assert.equal(order.descuento,10);});
test('fallo de guardado y validación no alteran el pedido',async()=>{const {c,nodes,order}=setup();let calls=0;c.apiPut=async()=>{calls++;throw Error('Red')};nodes.edit_discount_reason.value='';await c.confirmEditarProductos();assert.equal(calls,0);nodes.edit_discount_reason.value='Motivo';await c.confirmEditarProductos();assert.equal(order.descuento,0);nodes.edit_discount.value='101';await c.confirmEditarProductos();assert.equal(calls,1);});
test('conciliación aplica descuento a la factura seleccionada sin modificar líneas',()=>{const nodes={f_base:{},f_iva:{},financePreview:{}};const c=vm.createContext({document:{getElementById:id=>nodes[id]},financeSaving:false,financeEditor:{reconciliationLines:[{qty:10,price:10}],reconciliationTaxRatio:0.15},financePreview(){}});vm.runInContext(html.slice(html.indexOf('function reconciliationDiscountChange('),html.indexOf('function reconciliationAdd(')),c);c.reconciliationDiscountChange('10');assert.equal(nodes.f_base.value,'90.00');assert.equal(nodes.f_iva.value,'13.50');assert.equal(c.financeEditor.reconciliationLines[0].qty,10);});
test('scripts compilan',()=>{for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);});
