const test=require('node:test'),assert=require('node:assert/strict'),F=require('../lib/order-finance-core');
const order=()=>({factura:'F1',estado:'ENTREGADO',products:[{name:'Yum',qty:10,price:100},{name:'Cream',qty:5,price:20}],iva_tasa:15,descuento:0,entregas:[],pago:{abonos:[{monto:500}]},financial_data:{events:[],snapshots:[]}});
function input(o){return {type:'DESCUENTO_PRODUCTO',invoice:'F1',number:'F1',date:'2026-09-10',reason:'Descuento en factura omitido por vendedor',operation_key:'product-discount-0001',attachment:{name:'factura.pdf',url:'https://example.com/f.pdf'},base:99999,iva:150,lines:F.discountLines(o,'F1').map(r=>({name:r.name,mode:'percent',value:r.name==='Yum'?10:0}))};}
const add=(o,b)=>({...o,financial_data:F.append(o,b,{id:1},'2026-09-10T12:00:00Z')});
test('descuento en pedido entregado se calcula por servidor y no cambia productos ni abonos',()=>{const o=order(),before=JSON.stringify(o.products),next=add(o,input(o)),s=F.summary(next);assert.equal(s.base,1000);assert.equal(s.iva,150);assert.equal(s.net,1150);assert.equal(s.balance,650);assert.equal(JSON.stringify(next.products),before);assert.equal(next.estado,'ENTREGADO');assert.equal(next.pago.abonos[0].monto,500);assert.equal(next.financial_data.events[0].lineDiscounts[0].discount,100);});
test('dólares corresponden al total del producto y conserva IVA cero',()=>{const o=order();o.iva_tasa=0;const b=input(o);b.iva=0;b.lines[0]={name:'Yum',mode:'amount',value:25};const s=F.summary(add(o,b));assert.equal(s.base,1075);assert.equal(s.iva,0);});
test('corregir otra vez reemplaza el descuento anterior en vez de acumularlo',()=>{let o=order();o=add(o,input(o));const rows=F.discountLines(o,'F1');assert.equal(rows[0].value,10);let b={...input(o),operation_key:'product-discount-0002',iva:135};b.lines[0].value=20;o=add(o,b);assert.equal(F.summary(o).base,900);assert.equal(F.summary(o).credits,0);});
test('facturas parciales descuentan solo la cantidad de la factura seleccionada',()=>{const o=order();o.entregas=[{numeroFactura:'F1',items:[{name:'Yum',qty:4}]},{numeroFactura:'F2',items:[{name:'Yum',qty:6},{name:'Cream',qty:5}]}];const b=input(o);b.iva=54;const s=F.summary(add(o,b));assert.equal(s.invoices.find(i=>i.numero==='F1').total,414);assert.equal(s.invoices.find(i=>i.numero==='F2').total,805);});
test('rechaza descuentos excesivos, duplicados y productos inventados',()=>{const o=order();let b=input(o);b.lines[0].value=101;assert.throws(()=>add(o,b),/100/);b=input(o);b.lines[0]={name:'Yum',mode:'amount',value:1001};assert.throws(()=>add(o,b),/supera/);b=input(o);b.lines[1]=b.lines[0];assert.throws(()=>add(o,b),/repetido/);b=input(o);b.lines[0].name='Inventado';assert.throws(()=>add(o,b),/inválido/);});
test('no pierde correcciones globales anteriores ni interpreta su desglose sin datos',()=>{const o=order(),b={...input(o),type:'CORRECCION',base:800,iva:120};assert.throws(()=>F.discountLines(add(o,b),'F1'),/sin desglose/);});
test('reversión restaura la base anterior y mantiene el detalle de descuento',()=>{let o=order();o=add(o,input(o));o=add(o,{type:'REVERSO',target:'product-discount-0001',date:'2026-09-10',reason:'Error de registro',operation_key:'product-discount-0003'});assert.equal(F.summary(o).base,1100);assert.ok(o.financial_data.events[0].lineDiscounts);assert.equal(F.discountLines(o,'F1')[0].value,0);});
