'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const costs=require('../lib/product-costs'),bases=require('../lib/base-formulations'),products=require('../lib/product-master');
const recipe={id:3,version:2,data:{name:'Caramelo duro',yield_kg:8,labor:4,overhead:2,lines:[{mode:'inventory',kind:'material',item_id:1,quantity:10,unit:'kg'}]}};
const inventory=[{id:1,nombre:'Azúcar',unidad:'kg',tipo:'materia_prima',costo_prom:2}];
const base=()=>({...recipe,current:bases.calculate(recipe.data,inventory)});
const product=()=>({id:1,nombre:'YumYum',sku:'YUM-5',formula_id:3,ficha:{marca:'YumYum',presentacion:'Funda',peso_masa_g:5,unidades_presentacion:1000,peso_neto_kg:5,costos_adicionales:{empaques:2,componentes:0,proceso:1}}});
test('desglose de base incorpora rendimiento y suma adicionales una sola vez',()=>{const r=costs.calculate(product(),base());assert.equal(r.complete,true);assert.equal(r.rows[0].quantity,6.25);assert.equal(r.rows[0].amount,12.5);assert.equal(r.rows[1].amount,2.5);assert.equal(r.rows[2].amount,1.25);assert.equal(r.mass_per_presentation,16.25);assert.equal(r.total,19.25);assert.equal(r.per_piece,.01925);assert.equal(r.per_kg,3.85);});
test('actualización de materia prima se refleja por producto sin modificar receta o ficha',()=>{const p=product(),b=base(),old=JSON.stringify(p);b.current=bases.calculate(recipe.data,[{...inventory[0],costo_prom:3}]);const r=costs.calculate(p,b);assert.equal(r.total,25.5);assert.equal(JSON.stringify(p),old);});
test('faltantes no se sustituyen por cero; cero explícito sí es válido',()=>{const p=product();delete p.ficha.costos_adicionales;let r=costs.calculate(p,base());assert.equal(r.complete,false);assert.equal(r.total,null);assert.equal(r.known,16.25);p.ficha.costos_adicionales={empaques:0,componentes:0,proceso:0};r=costs.calculate(p,base());assert.equal(r.complete,true);assert.equal(r.total,16.25);});
test('base sin precio, sin vínculo o sin cantidades mantiene total incompleto',()=>{const p=product();assert.equal(costs.calculate(p,null).total,null);const b=base();b.current=bases.calculate(recipe.data,[{...inventory[0],costo_prom:0}]);assert.equal(costs.calculate(p,b).total,null);delete p.ficha.peso_masa_g;assert.equal(costs.calculate(p,base()).total,null);});
test('no calcula total con masa superior al peso neto ni convierte peso de despacho en peso neto',()=>{const p=product();p.ficha.peso_neto_kg=1;assert.equal(costs.calculate(p,base()).total,null);delete p.ficha.peso_neto_kg;p.peso_bulto=6;const r=costs.calculate(p,base());assert.equal(r.total,19.25);assert.equal(r.per_kg,null);});
test('ficha valida adicionales y conserva diferencia entre vacío y cero',()=>{let d=products.validate({nombre:'YumYum',costos_adicionales:{empaques:'',componentes:'0',proceso:'0.05'}});assert.equal(d.ficha.costos_adicionales.empaques,null);assert.equal(d.ficha.costos_adicionales.componentes,0);assert.equal(d.ficha.costos_adicionales.proceso,.05);assert.throws(()=>products.validate({nombre:'Yum',costos_adicionales:{empaques:-1}}),/inválido/);assert.equal(products.validate({nombre:'Yum'}).ficha.costos_adicionales,undefined);});
test('consulta usa transacción de lectura y no expone costos a facturación',async()=>{
 const sqls=[];let role='gerente';const db={release(){},async query(sql){sqls.push(sql);if(sql.includes('FROM users'))return {rows:[{id:1,role}]};if(sql.includes('FROM catalogo'))return {rows:[product()]};if(sql.includes('FROM inventario'))return {rows:inventory};if(sql.includes('FROM base_formulations'))return {rows:[recipe]};return {rows:[]};}};const pool={connect:async()=>db};const r=await costs.report(pool,1);assert.equal(r.rows[0].total,19.25);assert.equal(sqls[0],'BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');assert.ok(!sqls.some(s=>/^(UPDATE|INSERT|DELETE)/.test(s)));role='facturacion';await assert.rejects(costs.report(pool,1),{status:403});assert.equal(sqls.at(-1),'ROLLBACK');
});
test('centro de costos abre informe por SKU y mantiene Formulaciones separada',()=>{const html=fs.readFileSync(path.join(__dirname,'../frontend/index.html'),'utf8');assert.match(html,/v==='centro-costos'\)\{ html=pcView\(\);/);assert.match(html,/v==='formulaciones'\)\{html=bfView\(\);/);for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))new vm.Script(m[1]);});
